CREATE TABLE tblStudents(ID INT PRIMARY KEY, firstName VARCHAR(200) NOT NULL, lastName VARCHAR(200) NOT NULL);
CREATE TABLE tblGroups(id TEXT NOT NULL, groups TEXT NOT NULL, projectID TEXT);
CREATE TABLE tblGroups(id TEXT NOT NULL, groups TEXT NOT NULL, projectID TEXT);